spring.application.name=clinicManagement
# 1. Log c?a toàn b? ?ng d?ng ? m?c INFO
logging.level.root=INFO
# 2. Log c?a Hibernate/JPA ? m?c DEBUG (Xem SQL truy v?n)
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# 3. Log c?a package c? th? com.medical.service ? m?c TRACE
logging.level.com.medical.service=TRACE

# 1. ???ng d?n và tên file log
logging.file.name=logs/patient_web_service.log

# 2. C? ch? xoay vòng (Rotation) - Kích th??c t?i ?a c?a 1 file
logging.logback.rollingpolicy.max-file-size=2MB

# 3. ??nh d?ng tên file sau khi nén (T? ??ng nén thành .gz)
logging.logback.rollingpolicy.file-name-pattern=${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz

# 4. Th?i gian l?u tr? t?i ?a (7 ngày)
logging.logback.rollingpolicy.max-history=7

# 5. T?ng dung l??ng t?i ?a c?a t?t c? các file log (Tùy ch?n thêm ?? b?o v? ? c?ng)
logging.logback.rollingpolicy.total-size-cap=50MB