spring.application.name=bookStore

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Cho phép truy c?p file t?nh t? th? m?c uploads
spring.web.resources.static-locations=classpath:/static/,file:uploads/
