spring.application.name=milktea
spring.datasource.url=jdbc:postgresql://localhost:5432/milktea_db
spring.datasource.username=postgres
spring.datasource.password=123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true